version: 2
jobs:
  build:
    working_directory: ~/site_build
    docker:
      - image: circleci/php:7.1-apache-node
        environment:
          - MYSQL_HOST=127.0.0.1
      - image: mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test
          - MYSQL_ROOT_HOST=%
          - MYSQL_HOST=127.0.0.1
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - run:
          name: ini
          command: php -i
      - run:
          name: memory_limit
          command: echo -e "memory_limit = 1024M" | sudo tee /usr/local/etc/php/conf.d/php.ini > /dev/null
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Install extension
          command: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - run:
          name: Install Composer
          command: 'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'
      - run:
          name: Display versions
          command: |
            php -v
            composer --version
      - run:
          name: Install mysql-client
          command: |
            sudo apt-get install mysql-client
      - checkout
      - run: php -v
      - run: sudo cp .circleci/tests/circle/circle.conf /etc/apache2/sites-available
      - run: sudo a2ensite circle.conf
      - run: sudo a2enmod rewrite
      - run: composer global require drush/drush:8.*
      - run: sudo service apache2 restart
      # Set up Drupal
      #- run: bash setup.sh
      - run: echo 'export PATH=~/.composer/vendor/bin:$PATH' >> $BASH_ENV
      - run: composer install
      - run: cp .circleci/tests/circle/settings.php /home/circleci/site_build/web/sites/default/settings.local.php
      - run: ls web/sites/default
      # Add alias to drush configuration.
      - run: mkdir ~/.drush
      - run: echo '<?php' > ~/.drush/test.aliases.drushrc.php
      - run: drush status
      - run: pwd
      - run: ls ~/.ssh
      - run: drush site-alias @self --root=/home/circleci/site_build/web --full --with-optional
      - run: drush site-alias @self --root=/home/circleci/site_build/web --full --with-optional >> ~/.drush/test.aliases.drushrc.php
      - run: drush status --root=/home/circleci/site_build/web
      #- run: drush si oc --root=/home/circleci/site_build/web -y
      - run: cd /home/circleci/site_build/web
      - run: cp /home/circleci/site_build/drush/aliases.drushrc.php ~/.drush
      - run: cp /home/circleci/site_build/known_hosts ~/.ssh
      - run: chmod 600 ~/.ssh/known_hosts
      - run: cp /home/circleci/site_build/.circleci/worm_id_rsa.pub ~/.ssh
      - run: chmod 600 ~/.ssh/worm_id_rsa.pub
      #- run: cp /home/circleci/site_build/id_rsa ~/.ssh
      #- run: chmod 600 ~/.ssh/id_rsa
      - run: cp /home/circleci/site_build/.circleci/config ~/.ssh
      - run: chmod 600 ~/.ssh/config
      - run: drush status  --root=/home/circleci/site_build/web
      #- run: chmod 0600 /home/circleci/site_build/insecure_private_key
      #- run: cp /home/circleci/site_build/insecure_private_key ~/.ssh
      - run: cd /home/circleci/site_build/web/sites/default
      #- run: drush @self site-install oc -y
      # Install Drupal.
      - run:
          name: install
          command: drush @self si standard install_configure_form.enable_update_status_module=NULL -y
      # Import DB.
      - run:
          name: Drush cache
          command: drush cache-clear drush
      - run:
          name: Remote status
          command: drush @ecd8.dev status
      - run:
          name: Circle CI status
          command: drush @self status
      - run:
          name: SQL conf
          command: drush @self sql-conf
      - run:
          name: Export database
          command: drush @ecd8.dev sql-dump > db.sql
      - run:
          name: Import database
          command: drush @test sql-cli < db.sql -y
      # - run:
      #    name: Import config
      #    command: drush @test cim -y
      #- run:
      #    name: Run tests
      #    command: cd web/core; ../../vendor/bin/phpunit ../modules/custom/utexas_qualtrics_filter/tests/src/Unit/FilterQualtricsTest.php