name: Site-Install
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: /search404
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: oFGejEEA5thoklyMT_5vOvqJFtP4YzOvl3HxRH4jmC8
uuid: 3d0a7d5d-ade9-4d51-b2f5-dc8f0a934ba8
